### ISSUE TITLE
How to configure URL?

### ISSUE THREAD

**Issue by slava-vishnyakov** [SocialiteProviders/Jira#2]
How does one change the default `http://example.jira.com'`?

```
class Server extends BaseServer
{
    const JIRA_BASE_URL = 'http://example.jira.com';
```

The docs at http://socialiteproviders.github.io/providers/jira/ mention nothing about that.

**Comment by slava-vishnyakov** [comment]
And since the code uses `self::JIRA_BASE_URL` instead of `static::JIRA_BASE_URL` I can't even extend the `SocialiteProviders\Jira\Server` class with the new `const`... 

Please advise. Thanks.

**Comment by DraperStudio** [comment]
We are currently working on an improved way of configuration which will solve issues like this. Should be released soon.

**Comment by slava-vishnyakov** [comment]
It seems that it is already implemented in @vmichnowicz fork (also tests, nice!)
https://github.com/SocialiteProviders/Jira/compare/master...vmichnowicz:config-and-errors

Too bad I discovered that fork a little too late.
In the meantime it seems that our Atlassian Cloud instance has different fields, see here:

https://github.com/SocialiteProviders/Jira/compare/master...slava-vishnyakov:master#diff-af3a35ce5c2351f8166a976f20e499a4R27

**Comment by DraperStudio** [comment]
Guess you can use that one until we have our new configuration implemented. Wonder why he never send a PR with the changes he made.

**Comment by vmichnowicz** [comment]
@DraperStudio sorry, I was working on this for work and priories at work are constant changing so I didn't have any time to finish my work on this. :disappointed:

**Comment by DraperStudio** [comment]
@vmichnowicz Would you be able to finish it up anytime soon and send a PR or should I nitpick what I think would be useful and put it in myself?

**Comment by slava-vishnyakov** [comment]
Actually I also created a fork (much more hacky than @vmichnowicz version) :) but it solved the problem for me.

https://github.com/SocialiteProviders/Jira/compare/master...slava-vishnyakov:master

Thanks for the library, though. It works! :+1:

**Comment by vmichnowicz** [comment]
I don't think I have enough time to work on this anytime soon. The most recent code can be found in my branch here: https://github.com/vmichnowicz/Jira/tree/config-and-errors

I left off on the unit tests and I still need to test it a bit better too to make sure everything is working as expected.

**Comment by DraperStudio** [comment]
Alright, thanks for letting me know. I will try to find some time and pick up some of your changes.

Tests will soon be added to all providers one after another.

**Comment by DraperStudio** [comment]
@slava-vishnyakov Could you pull in the current `dev-master` and test if the changes I just pushed work to?

Once you have pulled it in you should configure these variables in your `.env` file.
```
JIRA_KEY=
JIRA_SECRET=
JIRA_REDIRECT_URI=
JIRA_BASE_URI=
JIRA_CERT_PATH=
```

I have no JIRA application to test it since it is a pain in the ass to set one up.

**Comment by slava-vishnyakov** [comment]
Hmmm... Strange, when I try to update - I get this:

```  [Composer\DependencyResolver\SolverProblemsException]
    Problem 1
      - Installation request for socialiteproviders/jira dev-master -> satisfiable by socialiteproviders/jira[dev-master].
      - socialiteproviders/jira dev-master requires socialiteproviders/manager ~2.1 -> no matching package found.```

I have this in composer.json

```{
        "laravel/framework": "5.2.*",
        "laravel/socialite": "2.*",
        "socialiteproviders/jira": "dev-master"
    }
....
    "minimum-stability": "dev"
```

**Comment by DraperStudio** [comment]
Hmm, I did `composer require socialiteproviders/jira:dev-master` and it worked without any issues.

**Comment by slava-vishnyakov** [comment]
Ok, so a complete `composer update` helped,

after update I've got this

```
  [Symfony\Component\Debug\Exception\FatalErrorException]
  Call to undefined method SocialiteProviders\Jira\Server::getConfig()


Script php artisan optimize handling the post-update-cmd event returned with an error


  [RuntimeException]
  Error Output: PHP Fatal error:  Call to undefined method SocialiteProviders\Jira\Server::getConfig() in ..../vendor/socialiteproviders/jira/src/Server.php on line 35
```

`php artisan serve` seems to also fail with the same

```
php artisan serve
PHP Fatal error:  Call to undefined method SocialiteProviders\Jira\Server::getConfig() in /Volumes/SSD130/PhpstormProjects/dr-visual-2/vendor/socialiteproviders/jira/src/Server.php on line 35


  [Symfony\Component\Debug\Exception\FatalErrorException]
  Call to undefined method SocialiteProviders\Jira\Server::getConfig()
````

The installed commit is:

```
  - Installing socialiteproviders/jira (dev-master 46868bf)
```

**Comment by DraperStudio** [comment]
Pushed https://github.com/SocialiteProviders/Jira/commit/da8fb4f6346614c46fd7b370b9f5548f21f95a71

Would it be possible that you provide me test credentials so that I could make this work local?

**Comment by slava-vishnyakov** [comment]
Sorry, can't do it, it's a large enterprise installation of JIRA.

**Comment by DraperStudio** [comment]
Ok, then please try https://github.com/SocialiteProviders/Jira/commit/da8fb4f6346614c46fd7b370b9f5548f21f95a71 with `composer update`

**Comment by slava-vishnyakov** [comment]
da8fb4f did install without error,

I have this in `.env` file

```
JIRA_BASE_URI=https://XXXXXX.jira.com
```

however I get the following errror:

```
Could not resolve host: example.jira.com [url] http://example.jira.com/plugins/servlet/oauth/request-token?...
````

**Comment by slava-vishnyakov** [comment]
To be clear, in config - it's not `example.jira.com`

**Comment by slava-vishnyakov** [comment]
If I do this:

```php
trait ConfigTrait
{
    protected $config;

    public function setConfig(Config $config)
    {
        $config = $config->get();
        dd(array_keys($config));
```

I see only this:

```
array:3 [▼
  0 => "client_id"
  1 => "client_secret"
  2 => "redirect"
]
```

`base_uri` is not in the list

**Comment by slava-vishnyakov** [comment]
Also, searching through the whole codebase (incl. vendor) I don't see any mentions of `JIRA_BASE_URI` at all..

**Comment by slava-vishnyakov** [comment]
Oh, I should add it to `config/services.php` Just a moment

**Comment by DraperStudio** [comment]
Pushed https://github.com/SocialiteProviders/Jira/commit/f8333e64d07cd597a085bec0420bbf2594267429

You won't find anything about `JIRA_BASE_URI` because this variable isn't defined anywhere. It gets loaded based on the `IDENTIFIER` and variables in the `additionalConfigKeys` method. Meaning it loads `IDENTIFIER_variableFromAdditionalConfigKeys` from the `.env` file.

There is no need anymore to add it to the `config/services.php`.

**Comment by slava-vishnyakov** [comment]
Ok, `f8333e6` seems to be working better, I've got to login to JIRA and press "allow", then I've go to callback stage,

I have this code:

```
    public function handleProviderCallback()
    {
        try {
            /** @var Provider $driver */
            $driver = \Socialize::driver('jira');
            $user = $driver->user();
```

However it fails with 
```
ErrorException in Provider.php line 20:
Trying to get property of non-object
in Provider.php line 20
at HandleExceptions->handleError('8', 'Trying to get property of non-object', '..../vendor/socialiteproviders/jira/src/Provider.php', '20', array('user' => array('accessTokenResponseBody' => null, 'token' => null, 'tokenSecret' => null, 'id' => null, 'nickname' => null, 'name' => 'vishnyakov', 'email' => null, 'avatar' => null))) in Provider.php line 20
at Provider->mapUserToObject(array('accessTokenResponseBody' => null, 'token' => null, 'tokenSecret' => null, 'id' => null, 'nickname' => null, 'name' => 'vishnyakov', 'email' => null, 'avatar' => null)) in AbstractProvider.php line 44
at AbstractProvider->user() in AuthController.php line 39
at AuthController->handleProviderCallback()
```

Seems to be referring to this:

```
    protected function mapUserToObject(array $user)
    {
        return (new User())->setRaw($user->extra)->map([
```

If I do `dd($user)` I get this:

```
array:8 [▼
  "accessTokenResponseBody" => null
  "token" => null
  "tokenSecret" => null
  "id" => null
  "nickname" => null
  "name" => "vishnyakov"
  "email" => null
  "avatar" => null
]
```

It seems to be an array and there is no `extra` field.

It seems that OnDemand JIRA (jira.com) might have different field structure than yours. Here's the code I've been using currently:

https://github.com/SocialiteProviders/Jira/compare/master...slava-vishnyakov:master#diff-af3a35ce5c2351f8166a976f20e499a4R21 

(see `src/Provider.php`, can't link to that part)

For ex., we have field `emailAddress`, not `email`, etc.. (see code)

But still, the object that comes is empty for some reason...

**Comment by DraperStudio** [comment]
Hmm, could you go to `SocialiteProviders\Manager\OAuth1\AbstractProvider` and do a `dd($token);` before this line https://github.com/SocialiteProviders/Manager/blob/master/src/OAuth1/AbstractProvider.php#L44?

Seems like something is going wrong with the `getUserDetails` method. Could you also do a `dd` in the `urlUserDetails` method (https://github.com/SocialiteProviders/Jira/blob/master/src/Server.php#L105-L108) to see which url it tries to send the request to after you come back from JIRA?

**Comment by slava-vishnyakov** [comment]
So, the first `$token` is so:

```
array:2 [▼
  "tokenCredentials" => TokenCredentials {#185 ▼
    #identifier: "vx...[sensitive data removed]..."
    #secret: "np...[sensitive data removed]..."
  }
  "credentialsResponseBody" => EntityBody {#207 ▼
    #contentEncoding: false
    #rewindFunction: null
    #stream: stream resource @288 }
    #size: null
    #cache: array:9 [▼
      "wrapper_type" => "PHP"
      "stream_type" => "TEMP"
      "mode" => "w+b"
      "unread_bytes" => 0
      "seekable" => true
      "uri" => "php://temp"
      "is_local" => true
      "is_readable" => true
      "is_writable" => true
    ]
    #customData: array:1 [▼
      "default" => true
    ]
  }
]
```

The second `urlUserDetails` is so:
```
    public function urlUserDetails()
    {
        dd([
             empty($this->jiraUserDetailsUrl), 
             $this->getJiraBaseUrl().'/rest/api/2/myself', 
             $this->jiraUserDetailsUrl
        ]);
        return empty($this->jiraUserDetailsUrl) ? $this->getJiraBaseUrl().'/rest/api/2/myself' : $this->jiraUserDetailsUrl;
    }
```
```
array:3 [▼
  0 => true
  1 => "https://XXXXXXXXX.jira.com/rest/api/2/myself"
  2 => null
]
```

where XXXXXXX is correct URL

**Comment by DraperStudio** [comment]
Alright looks like it is supposed to look like. 

Could you go back to https://github.com/SocialiteProviders/Manager/blob/master/src/OAuth1/AbstractProvider.php#L44 and do `dd($this->server->getUserDetails($tokenCredentials))` to see how the response looks like or if it is empty?

This should be the data that will be fed into the User object so I could update it.

**Comment by slava-vishnyakov** [comment]
Yep, it has something:

```
TokenCredentials {#185 ▼
  #identifier: "g5k...."
  #secret: "s59..."
}
```

I have some suspicion. 
The provider requires that I write _something_ in `JIRA_SECRET`, so I wrote `123` there.
In previous version (that I forked and it got working) - this was empty at all (and yet worked)

**Comment by slava-vishnyakov** [comment]
I also can't find `secret` in JIRA - there's only `consumer key` and that's about that.

**Comment by DraperStudio** [comment]
The `TokenCredentials` is what is returned by `dd($this->server->getUserDetails($tokenCredentials))`?

```
JIRA_KEY = client id/consumer key
JIRA_SECRET = client secret/consumer secret/token secret
```

**Comment by slava-vishnyakov** [comment]
No, the `TokenCredentials` are very different. Also, they are different on each try.

**Comment by DraperStudio** [comment]
Then what do you see when you do `dd($this->server->getUserDetails($tokenCredentials))`? It should be an array or any other data struct but not `TokenCredentials`.

**Comment by slava-vishnyakov** [comment]
An array, like so:

```
User {#182 ▼
  +accessTokenResponseBody: null
  +token: null
  +tokenSecret: null
  +id: null
  +nickname: null
  +name: "vishnyakov"
  +email: null
  +avatar: null
}
```

**Comment by slava-vishnyakov** [comment]
Sorry, `User` object

**Comment by DraperStudio** [comment]
Hmm, the issue seems to be in the `userDetails` method in the `Server` class.

https://github.com/SocialiteProviders/Jira/blob/master/src/Server.php#L113-L121

Could you do a `dd($data);` before the `$user = new User();` line?

**Comment by slava-vishnyakov** [comment]
Yep, there's data there in `array`:

```
array:12 [
  "self" => "https://XXXXXXXXXXXXX.jira.com/rest/api/2/user?username=vishnyakov"
  "key" => "vishnyakov"
  "name" => "vishnyakov"
  "emailAddress" => "xxxxxxxx@xxxxx.com"
  "avatarUrls" => array:4 [
    "16x16" => "https://XXXXXXXXXXXXX.jira.com/secure/useravatar?size=xsmall&ownerId=vishnyakov&avatarId=10441"
    "24x24" => "https://XXXXXXXXXXXXX.jira.com/secure/useravatar?size=small&ownerId=vishnyakov&avatarId=10441"
    "32x32" => "https://XXXXXXXXXXXXX.jira.com/secure/useravatar?size=medium&ownerId=vishnyakov&avatarId=10441"
    "48x48" => "https://XXXXXXXXXXXXX.jira.com/secure/useravatar?ownerId=vishnyakov&avatarId=10441"
  ]
  "displayName" => "Vyacheslav Vishnyakov"
  "active" => true
  "timeZone" => "Europe/Berlin"
  "locale" => "en_US"
  "groups" => array:2 [
    "size" => 12
    "items" => []
  ]
  "applicationRoles" => array:2 [
    "size" => 1
    "items" => []
  ]
  "expand" => "groups,applicationRoles"
]
```

**Comment by DraperStudio** [comment]
Could you replace these methods in your local copy and see if that works?

*Server.php*
```php
public function userDetails($data, TokenCredentials $tokenCredentials)
{
    return $data;
}
```

*Provider.php*
```php
protected function mapUserToObject(array $user)
{
    return (new User())->setRaw($user)->map([
        'id' => array_get($user, 'key'),
        'nickname' => array_get($user, 'name'),
        'name' => array_get($user, 'displayName'),
        'email' => array_get($user, 'emailAddress'),
        'avatar' => array_get($user, 'avatarUrls.48x48'),
    ]);
}
```

**Comment by slava-vishnyakov** [comment]
This works:

```php
public function userDetails($data, TokenCredentials $tokenCredentials)
{
    return $data;
}
```

```php
    protected function mapUserToObject(array $user)
    {
        $userObject = (new User());

        if (isset($user['extra'])) {
            $userObject = $userObject->setRaw($user['extra']);
        }

        return $userObject->map([
            'id' => array_get($user, 'key'),
            'nickname' => array_get($user, 'nickname', array_get($user, 'name')),
            'name' => array_get($user, 'displayName', array_get($user, 'name')),
            'email' => array_get($user, 'emailAddress', array_get($user, 'email')),
            'avatar' => array_get($user, 'avatarUrls.48x48', array_get($user, 'avatar')),
            'active' => array_get($user, 'active'),
            'timezone' => array_get($user, 'timeZone'),
            'locale' => array_get($user, 'locale'),
        ]);

        return $userObject;
    }
```

**Comment by slava-vishnyakov** [comment]
I left the old fields for compatibility with your original code, but overriding them if new ones exist.

**Comment by DraperStudio** [comment]
Alright, this looks good. I have pushed https://github.com/SocialiteProviders/Jira/commit/03643566b43087178a8b0b86837c561664725053 so you can do a `composer update` and test if the provider now works.

**Comment by slava-vishnyakov** [comment]
👍  Perfect! Works now.

Thank you very much!

1) Can we make `JIRA_SECRET` optional? It seems that it's not used and it's confusing to fill it with random data.

2) Also, it would be useful to have this in docs - I've had to search GitHub issues to find how to do this:

```
You also need to generate key pair:

    mkdir storage/app/keys
    openssl genrsa -out storage/app/keys/jira.pem 1024
    openssl rsa -in storage/app/keys/jira.pem -pubout -out storage/app/keys/jira.pub

Your key is now in storage/app/keys/jira.pub
```

**Comment by DraperStudio** [comment]
I will think about a way of making `JIRA_SECRET` optional since this is handled by the Manager package at the moment.

------

I will add this to the docs as soon as @AndyWendt has updated them with the configuration details.

**Comment by slava-vishnyakov** [comment]
Excellent! Thanks for the fixes!

**Comment by DraperStudio** [comment]
@slava-vishnyakov You can now pull in the `2.1.0` stable and I will add the optional `JIRA_SECRET` in `2.1.1`
