### ISSUE TITLE
Missing dependency?

### ISSUE THREAD

**Issue by simonfranz** [SocialiteProviders/Jira#4]
Hi there,
In the RsaSha1Signature there is guzzle referenced but no included in the composer.json dependencies

https://github.com/SocialiteProviders/Jira/blob/master/src/RsaSha1Signature.php

Best Regards

**Comment by simonfranz** [comment]
Digging around, the error seems to be somewhere else. 
In the require-chain to laravel/socialite there is guzzle required in https://github.com/laravel/socialite/blob/2.0/composer.json

Despite that I'm getting the error
```
FatalThrowableError in RsaSha1Signature.php line 62:
Class 'Guzzle\Http\Url' not found
```

Maybe someone has an idea?

**Comment by DraperStudio** [comment]
Thanks a lot for filing this issue! Would you like to write a patch for this?

**Comment by simonfranz** [comment]
Yes, but it could take some time. After I sucessfully logged in in jira i'll do a PR.
